[package]
name = "rust"
version = "0.1.0"
authors = ["rrokkam <rohithrokkam@gmail.com>"]
edition = "2018"

[dependencies]
enum_dispatch = "0.3"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["constructor"]
